copilot-platforms/profile-manager

- src/app/page.tsx
> fix profileLinks issue

- .github/workflows/lint.yml
- package.json
Ref: [OUT-101](https://linear.app/copilotplatforms/issue/OUT-101/update-latest-copilot-sdk-on-all-3-apps)
Changes:
- Package json already included `^1.2.0` so just update workflow for profile-manager
> OUT-101 | Update latest copilot SDK on all 3 apps

- src/app/api/client-profile-updates/route.ts
- src/types/common.ts
Ref: https://linear.app/copilotplatforms/issue/OUT-107/server-component-render-error-on-profile-manager-in-prod
Changes:
- Update schemas to accept null values to prevent zod error
> OUT-107 | Server Component Render error on Profile Manager in prod

- src/app/manage/page.tsx
- src/components/atoms/Button.tsx
- src/components/atoms/RedirectButton.tsx
- src/types/copilotPortal.ts
- src/utils/copilotLinks.ts
- yarn.lock
Ref:
- [OUT-100](https://linear.app/copilotplatforms/issue/OUT-100/client-preview-other-settings-link)
Changes:
- Add component for Button
- Make links in manage page clickable
> OUT-100 | Client Preview: Other Settings Link

- src/app/page.tsx
Ref:
- [OUT-152](https://linear.app/copilotplatforms/issue/OUT-152/zod-error-on-profile-manager)
Changes:
- Fix token being parsed from object when it expects string
> OUT-152 | Zod error on profile manager

- src/types/copilotPortal.ts
We made a couple updates to the redirect bridge routes. This PR makes those updates.
> chore: fix redirect paths

- src/app/manage/page.tsx
Account settings link should take client to the settings/profile page instead of the general settings page
> change profile link

- .env.example
- src/app/api/client-profile-updates/route.ts
- src/components/table/Table.tsx
- src/components/table/cellRenderers/ClientCellRenderer.tsx
- src/components/table/cellRenderers/CompanyCellRenderer.tsx
- src/components/table/cellRenderers/HistoryCellRenderer.tsx
- src/lib/helper.ts
Ref:
- [OUT-160](https://linear.app/copilotplatforms/issue/OUT-160)
- [OUT-165](https://linear.app/copilotplatforms/issue/OUT-165)
- [OUT-158](https://linear.app/copilotplatforms/issue/OUT-158)
- [OUT-164](https://linear.app/copilotplatforms/issue/OUT-164)
Changes:
- See ref
> OUT-165 | OUT-160 | OUT-158 | OUT-164 | High priority profile manager bugs

- .env.example
- prisma/migrations/20240313124911_add_was_updated_by_iu_key_to_client_profile_updates/migration.sql
- prisma/schema.prisma
- src/app/api/client-profile-updates/route.ts
- src/app/api/client-profile-updates/services/clientProfileUpdates.service.ts
- src/components/table/Table.tsx
- src/components/table/cellRenderers/ClientCellRenderer.tsx
- src/components/table/cellRenderers/CompanyCellRenderer.tsx
- src/components/table/cellRenderers/HistoryCellRenderer.tsx
- src/lib/helper.ts
- src/types/clientProfileUpdates.ts
Ref: [OUT-161](https://linear.app/copilotplatforms/issue/OUT-161/first-log-is-shown-as-empty-when-custom-field-had-a-value-before)
NOTE: Merge after OUT-160
Changes:
- Add new column in ClientProfileUpdates to check if change was created by IU
- Fetch IU change history in tooltip only, and not updates list
> OUT-161 | First log is shown as empty when custom field had a value before

- src/app/api/client-profile-updates/route.ts
- src/lib/helper.ts
Ref:
- [OUT-183](https://linear.app/copilotplatforms/issue/OUT-183/empty-multi-select-field-values-are-now-showing-as-an-update)
- [OUT-184](https://linear.app/copilotplatforms/issue/OUT-184)
Changes:
- Change code to properly compare pass by reference data types like arrays/objects.
> OUT-184 | OUT-183 | Bugs related to array comparison

- src/components/table/Table.tsx
Keeping the default state as we had it before to allow the link to work
> Undo no rows overlay

- src/components/table/cellRenderers/HistoryCellRenderer.tsx
Ref: [OUT-218](https://linear.app/copilotplatforms/issue/OUT-218/not-showing-that-client-cleared-out-phone-number)
Changes:
- Fix tricky issue where phone number was not displaying changed
> OUT-218 | Not showing that client cleared out phone number

- src/app/manage/views/ManagePageContainer.tsx
[OUT-225 : TypeError: Cannot read properties of null (reading 'phoneNumber')](https://linear.app/copilotplatforms/issue/OUT-225/typeerror-cannot-read-properties-of-null-reading-phonenumber
> fix nullpointer when custom fields is null

- package.json
- src/app/manage/page.tsx
- src/app/page.tsx
- src/components/table/Table.tsx
- src/context/index.tsx
- src/hoc/ContextUpdate.tsx
- src/utils/fetcher.ts
- yarn.lock
Ref: [OUT-229](https://linear.app/copilotplatforms/issue/OUT-229/add-swr-for-real-time-updates-to-iu-side-of-profile-manager)
Changes:
- Add SWR package
- Change appState to support loading state for SWR
- Use client-side polling SWR instead of server side fetch
> OUT-229 | Add SWR for Real Time Updates to IU side of Profile Manager

- src/app/api/client-profile-updates/services/clientProfileUpdates.service.ts
- src/app/api/profile-update-history/route.ts
- src/components/table/cellRenderers/HistoryCellRenderer.tsx
- src/types/clientProfileUpdates.ts
Ref: [OUT-206](https://linear.app/copilotplatforms/issue/OUT-206/extraneous-empty-in-the-log)
Changes:
- use `wasUpdatedByIU` to check if history 
- (i) length is less than 4
- (ii) most oldest is updated by IU
Then treat it as first history was created by IU
> OUT-206 | Extraneous empty in the log

- .gitignore
- docker-compose.yml
- next.config.js
- package.json
- sentry.client.config.ts
- sentry.edge.config.ts
- sentry.server.config.ts
- src/instrumentation.ts
- yarn.lock
> Implement Sentry sourcemaps

- src/app/api/client-profile-updates/route.ts
> OUT-841 Profile Manager: IU View for Profile Manager is shown as blank

- sentry.client.config.ts
- sentry.edge.config.ts
- sentry.server.config.ts
- src/app/api/client-profile-updates/route.ts
> Test: Profile Manager: IU View for Profile Manager is shown as blank

- src/components/table/Table.tsx
> OUT-844 TypeError: Cannot read properties of undefined (reading 'avatarImageUrl')

- src/components/table/cellRenderers/ClientCellRenderer.tsx
> OUT-860 TypeError: Cannot read properties of undefined (reading '0')

- src/app/NoPreviewSupport.tsx
- src/app/manage/page.tsx
- src/app/page.tsx
- src/utils/copilotApiUtils.ts
- src/utils/previewMode.ts
> OUT-1214 | Disable preview mode feature in profile manager

- src/app/manage/views/ManagePageContainer.tsx
> OUT-1301 | Fix address value showing up as [object Object]

- src/app/api/client-profile-updates/route.ts
> OUT-1302 | Fix second history appearing twice in address field History Popup
